name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Go
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      # Build the application
      - name: Build application
        run: |
          go build -o api-template cmd/main.go
        env:
          CGO_ENABLED: 0
          GOOS: linux
          GOARCH: amd64

      # Upload the binary
      - name: Upload binary to server
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: ./api-template
          target: /develop/go-template-api/api-template

      # Run the application
      - name: Run application
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /develop/go-template-api
            chmod +x api-template
            nohup ./api-template > api-template.log 2>&1 &